# Generated by Django 5.2.1 on 2025-06-17 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maquina', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=20)),
                ('vulnerabilidades', models.TextField()),
                ('recomendaciones', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('message_type', models.CharField(choices=[('security-audit', 'Auditoría de Seguridad'), ('network-implementation', 'Implementación de Redes'), ('penetration-testing', 'Penetration Testing'), ('consulting', 'Consultoría General'), ('other', 'Otro')], max_length=50)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
